-- Store-level access assignments for client portal users.

create table if not exists public.client_user_stores (
  id bigint generated by default as identity primary key,
  client_user_id uuid not null references public.client_users (id) on delete cascade,
  store_id bigint not null,
  created_at timestamptz not null default now(),
  constraint client_user_stores_user_store_unique unique (client_user_id, store_id)
);

create index if not exists client_user_stores_client_user_id_idx
  on public.client_user_stores (client_user_id);

create index if not exists client_user_stores_store_id_idx
  on public.client_user_stores (store_id);

alter table public.client_user_stores enable row level security;

drop policy if exists "Authenticated users can read client user stores" on public.client_user_stores;
create policy "Authenticated users can read client user stores"
  on public.client_user_stores
  for select
  to authenticated
  using (true);

drop policy if exists "Authenticated users can insert client user stores" on public.client_user_stores;
create policy "Authenticated users can insert client user stores"
  on public.client_user_stores
  for insert
  to authenticated
  with check (true);

drop policy if exists "Authenticated users can delete client user stores" on public.client_user_stores;
create policy "Authenticated users can delete client user stores"
  on public.client_user_stores
  for delete
  to authenticated
  using (true);
